// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Node scripts (unlike Next.js itself) don't auto-load .env.local, and this
// project keeps DATABASE_URL there rather than in a plain .env.
config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
   seed: "prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
